<a href="https://colab.research.google.com/github/sumusa/Hamoye-Internship-Notes/blob/master/Hamoye_Stage_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Python for Machine Learning
###NumPy Array and Vectorization

In [2]:
#convention for importing numpy
import numpy as np

In [3]:
arr = [6,7,8,9]
print(type(arr))

<class 'list'>


In [4]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(4,)


In [6]:
print(a.dtype)

int64


In [7]:
#get the dimension of 'a'
print(a.ndim)
#a is a 1d array with 4 items

1


In [8]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
print(b.ndim)
b.shape
#b is a 2d array with 2 rows and 3 columns

2


(2, 3)

In [10]:
#to generate a 2*3 array with random values
np.random.random((2,3))

array([[0.10066076, 0.926736  , 0.71149794],
       [0.52394334, 0.44639474, 0.67634142]])

In [11]:
#to generate a 2*3 array of zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#to generate a 2*3 array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
#to genarate a 3*3 identity matrix
np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [15]:
#intra-operability of arrays and scalars
c = np.array([[9.0, 8.0, 7.0],[1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0],[9.0, 8.0, 7.0]])
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [16]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [17]:
c**2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [18]:
#indexing with arrays and using arrays for data processing
a[0]

6

In [19]:
b[1,2]

6

In [20]:
c[0,1]

8.0

In [21]:
d[1, 0:2]

array([9., 8.])

In [22]:
e = np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])
e[:3, :2] #slicing

array([[10, 11],
       [13, 14],
       [16, 17]])

In [23]:
#integer indexing
e[[2,0,3,1],[2,1,0,2]]

array([18, 11, 19, 15])

In [24]:
#boolean indexing meeting a specified condition
e[e>15]

array([16, 17, 18, 19, 20, 21])

###Pandas

In [25]:
import pandas as pd

In [26]:
days = pd.Series(['Monday','Tuesday','Wednesday'])
print(days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [27]:
#creating series with numpy arrays
days_list = np.array(['Monday','Tuesday','Wednesday'])
numpy_days = pd.Series(days_list)
print(numpy_days)
print(days_list)

0       Monday
1      Tuesday
2    Wednesday
dtype: object
['Monday' 'Tuesday' 'Wednesday']


In [28]:
#using strings as index
days = pd.Series(['Monday','Tuesday','Wednesday'], index = ['a','b','c'])
#create series from a dictionary
days1 = pd.Series({'a':'Monday','b':'Tuesday','c':'Wednesday'})
print(days)
print(days1)

a       Monday
b      Tuesday
c    Wednesday
dtype: object
a       Monday
b      Tuesday
c    Wednesday
dtype: object


In [29]:
#accessing series using specified index
days[0]

'Monday'

In [30]:
days[1: ]

b      Tuesday
c    Wednesday
dtype: object

In [31]:
days['c']

'Wednesday'

In [32]:
#print an empty dataframe
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []


In [33]:
#create a dataframe from a dictionary
df_dict = {'Country': ['Ghana','Kenya','Nigeria','Togo'], 
           'Capital': ['Accra', 'Nairobi', 'Abuja','Lome'],
           'Population': [10000, 8500, 35000, 12000],
           'Age': [60, 70, 80, 75]
           }

In [34]:
df = pd.DataFrame(df_dict, index = [2,4,6,8])
print(df)

   Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75


In [35]:
df_list = [['Ghana','Accra', 10000, 60],
           ['Kenya','Nairobi', 8500, 70],
           ['Nigeria','Abuja', 35000, 80],
           ['Togo','Lome', 12000, 75]] 

In [36]:
df1 = pd.DataFrame(df_list, index = [2,4,6,8], columns = 
                   ['Country','Capital','Population','Age'])
print(df1)

   Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75


In [37]:
#selects the row at index 3
df.iloc[3]

Country        Togo
Capital        Lome
Population    12000
Age              75
Name: 8, dtype: object

In [42]:
#select row with index label 3
df.loc[6]

Country       Nigeria
Capital         Abuja
Population      35000
Age                80
Name: 6, dtype: object

In [39]:
#select Capital column
df['Capital']

2      Accra
4    Nairobi
6      Abuja
8       Lome
Name: Capital, dtype: object

In [43]:
df.at[6, 'Country']

'Nigeria'

In [44]:
df.iat[2,0]

'Nigeria'

In [45]:
#summary and descriptive stats in pandas
df['Population'].sum()

65500

In [46]:
df.mean()

Population    16375.00
Age              71.25
dtype: float64

In [47]:
df.describe()

Population        Age
count      4.000000   4.000000
mean   16375.000000  71.250000
std    12499.166639   8.539126
min     8500.000000  60.000000
25%     9625.000000  67.500000
50%    11000.000000  72.500000
75%    17750.000000  76.250000
max    35000.000000  80.000000

In [48]:
#handling missing data
df_dict2 = {'Name':['James','Yemen','Caro', np.nan],
            'Profession':['Researcher','Artist','Doctor','Writer'],
            'Experience':[12, np.nan, 10, 8],
            'Height': [np.nan, 175, 180, 150]}
new_df = pd.DataFrame(df_dict2)
new_df

Name  Profession  Experience  Height
0  James  Researcher        12.0     NaN
1  Yemen      Artist         NaN   175.0
2   Caro      Doctor        10.0   180.0
3    NaN      Writer         8.0   150.0

In [49]:
new_df.isnull() #check for cells with missing values

Name  Profession  Experience  Height
0  False       False       False    True
1  False       False        True   False
2  False       False       False   False
3   True       False       False   False

In [50]:
#remove rows with missing values
new_df.dropna()

Name Profession  Experience  Height
2  Caro     Doctor        10.0   180.0

###Data Types and Data Wrangling

In [51]:
csv_df = pd.read_csv('sample_file.csv')
csv_df.to_csv('sample_file.csv',index=False)

FileNotFoundError: ignored

In [52]:
excel_df = pd.read_excel('sample_file.xlsx')
excel_df.to_excel('sample_file.xlsx')

FileNotFoundError: ignored

In [53]:
html_df = pd.read_html('http://www.webpage.com/sampledata.html')
html_df.to_html('sample_file.html')

HTTPError: ignored

In [54]:
#read in the fuel dataset
url = 'https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv'
fuel_data = pd.read_csv(url, error_bad_lines = False)
fuel_data.describe(include = 'all')

record_id  ...  fuel_cost_per_mmbtu
count                     29523  ...         29523.000000
unique                    29523  ...                  NaN
top     f1_fuel_2000_12_31_0_13  ...                  NaN
freq                          1  ...                  NaN
mean                        NaN  ...            19.304354
std                         NaN  ...          2091.540939
min                         NaN  ...           -41.501000
25%                         NaN  ...             1.940000
50%                         NaN  ...             4.127000
75%                         NaN  ...             7.745000
max                         NaN  ...        359278.000000

[11 rows x 11 columns]

In [55]:
fuel_data.head()

record_id  ...  fuel_cost_per_mmbtu
0   f1_fuel_1994_12_1_0_7  ...                1.121
1  f1_fuel_1994_12_1_0_10  ...                1.120
2   f1_fuel_1994_12_2_0_1  ...                1.650
3   f1_fuel_1994_12_2_0_7  ...                1.970
4  f1_fuel_1994_12_2_0_10  ...                2.570

[5 rows x 11 columns]

In [56]:
fuel_data.shape

(29523, 11)

In [57]:
fuel_data.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [58]:
#use groupby to count the sum of each unique value in the fuel unit column
fuel_data.groupby('fuel_unit')['fuel_unit'].count()

fuel_unit
bbl        7998
gal          84
gramsU      464
kgU         110
mcf       11354
mmbtu       180
mwdth        95
mwhth       100
ton        8958
Name: fuel_unit, dtype: int64

In [61]:
fuel_data[['fuel_unit']] = fuel_data[['fuel_unit']].fillna(value = 'mcf')

In [62]:
#check if missing values have been filled
fuel_data.isnull().sum()

record_id                       0
utility_id_ferc1                0
report_year                     0
plant_name_ferc1                0
fuel_type_code_pudl             0
fuel_unit                       0
fuel_qty_burned                 0
fuel_mmbtu_per_unit             0
fuel_cost_per_unit_burned       0
fuel_cost_per_unit_delivered    0
fuel_cost_per_mmbtu             0
dtype: int64

In [63]:
fuel_data.groupby('report_year')['report_year'].count()

report_year
1994    1235
1995    1201
1996    1088
1997    1094
1998    1107
1999    1050
2000    1373
2001    1356
2002    1205
2003    1211
2004    1192
2005    1269
2006    1243
2007    1264
2008    1228
2009    1222
2010    1261
2011    1240
2012    1243
2013    1199
2014    1171
2015    1093
2016    1034
2017     993
2018     951
Name: report_year, dtype: int64

In [65]:
fuel_data.groupby('fuel_type_code_pudl').first()
#group by the fuel type code and print the first entries in all the groups formed

record_id  ...  fuel_cost_per_mmbtu
fuel_type_code_pudl                          ...                     
coal                  f1_fuel_1994_12_1_0_7  ...                1.121
gas                  f1_fuel_1994_12_2_0_10  ...                2.570
nuclear               f1_fuel_1994_12_2_1_1  ...                0.450
oil                   f1_fuel_1994_12_6_0_2  ...                5.469
other                f1_fuel_1994_12_11_0_6  ...                2.335
waste                 f1_fuel_1994_12_9_0_3  ...                1.072

[6 rows x 10 columns]

In [66]:
fuel_df1 = fuel_data.iloc[0:19000].reset_index(drop=True)
fuel_df2 = fuel_data.iloc[19000: ].reset_index(drop=True)

In [67]:
#check that the length of both dataframes sum to the expected length
assert len(fuel_data) == (len(fuel_df1) + len(fuel_df2))

In [68]:
#an inner merge will lose rows that do not match in both dataframes
pd.merge(fuel_df1, fuel_df2, how = "inner")

Empty DataFrame
Columns: [record_id, utility_id_ferc1, report_year, plant_name_ferc1, fuel_type_code_pudl, fuel_unit, fuel_qty_burned, fuel_mmbtu_per_unit, fuel_cost_per_unit_burned, fuel_cost_per_unit_delivered, fuel_cost_per_mmbtu]
Index: []

In [69]:
#outer merge returns all rows in both dataframes
pd.merge(fuel_df1, fuel_df2, how = "outer")

record_id  ...  fuel_cost_per_mmbtu
0        f1_fuel_1994_12_1_0_7  ...                1.121
1       f1_fuel_1994_12_1_0_10  ...                1.120
2        f1_fuel_1994_12_2_0_1  ...                1.650
3        f1_fuel_1994_12_2_0_7  ...                1.970
4       f1_fuel_1994_12_2_0_10  ...                2.570
...                        ...  ...                  ...
29518  f1_fuel_2018_12_12_0_13  ...                9.030
29519   f1_fuel_2018_12_12_1_1  ...                6.950
29520  f1_fuel_2018_12_12_1_10  ...                8.990
29521  f1_fuel_2018_12_12_1_13  ...                1.110
29522  f1_fuel_2018_12_12_1_14  ...               11.680

[29523 rows x 11 columns]

In [70]:
#remove rows from the right dataframe that do not have a match with the left
#keeps all rows from the left
pd.merge(fuel_df1, fuel_df2, how = "left")

record_id  ...  fuel_cost_per_mmbtu
0         f1_fuel_1994_12_1_0_7  ...                1.121
1        f1_fuel_1994_12_1_0_10  ...                1.120
2         f1_fuel_1994_12_2_0_1  ...                1.650
3         f1_fuel_1994_12_2_0_7  ...                1.970
4        f1_fuel_1994_12_2_0_10  ...                2.570
...                         ...  ...                  ...
18995   f1_fuel_2009_12_182_1_9  ...                4.711
18996  f1_fuel_2009_12_182_1_10  ...               14.634
18997  f1_fuel_2009_12_182_1_13  ...                1.107
18998  f1_fuel_2009_12_182_1_14  ...               15.102
18999    f1_fuel_2009_12_79_0_1  ...                1.727

[19000 rows x 11 columns]

In [71]:
#check for duplicate rows
fuel_data.duplicated().any()

False