<a href="https://colab.research.google.com/github/sumusa/Hamoye-Internship-Notes/blob/master/Hamoye_Stage_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###NumPy Array and Vectorization

In [1]:
#convention for importing numpy
import numpy as np

In [2]:
arr = [6,7,8,9]
print(type(arr))

<class 'list'>


In [3]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a.shape)

(4,)


In [7]:
print(a.dtype)

int64


In [8]:
#get the dimension of 'a'
print(a.ndim)
#a is a 1d array with 4 items

1


In [10]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
print(b.ndim)
b.shape
#b is a 2d array with 2 rows and 3 columns

2


(2, 3)

In [13]:
#to generate a 2*3 array with random values
np.random.random((2,3))

array([[0.85415421, 0.57246884, 0.41852863],
       [0.77369179, 0.07334472, 0.926546  ]])

In [14]:
#to generate a 2*3 array of zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#to generate a 2*3 array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
#to genarate a 3*3 identity matrix
np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [20]:
#intra-operability of arrays and scalars
c = np.array([[9.0, 8.0, 7.0],[1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0],[9.0, 8.0, 7.0]])
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [21]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [22]:
c**2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [23]:
#indexing with arrays and using arrays for data processing
a[0]

6

In [24]:
b[1,2]

6

In [25]:
c[0,1]

8.0

In [26]:
d[1, 0:2]

array([9., 8.])

In [27]:
e = np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])
e[:3, :2] #slicing

array([[10, 11],
       [13, 14],
       [16, 17]])

In [28]:
#integer indexing
e[[2,0,3,1],[2,1,0,2]]

array([18, 11, 19, 15])

In [29]:
#boolean indexing meeting a specified condition
e[e>15]

array([16, 17, 18, 19, 20, 21])

###Pandas