<a href="https://colab.research.google.com/github/sumusa/Hamoye-Internship-Notes/blob/master/Hamoye_Stage_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Python for Machine Learning
###NumPy Array and Vectorization

In [2]:
#convention for importing numpy
import numpy as np

In [3]:
arr = [6,7,8,9]
print(type(arr))

<class 'list'>


In [4]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(4,)


In [6]:
print(a.dtype)

int64


In [7]:
#get the dimension of 'a'
print(a.ndim)
#a is a 1d array with 4 items

1


In [8]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
print(b.ndim)
b.shape
#b is a 2d array with 2 rows and 3 columns

2


(2, 3)

In [10]:
#to generate a 2*3 array with random values
np.random.random((2,3))

array([[0.54472973, 0.08180019, 0.62037523],
       [0.19083023, 0.94696013, 0.06796162]])

In [11]:
#to generate a 2*3 array of zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
#to generate a 2*3 array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
#to genarate a 3*3 identity matrix
np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [15]:
#intra-operability of arrays and scalars
c = np.array([[9.0, 8.0, 7.0],[1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0],[9.0, 8.0, 7.0]])
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [16]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [17]:
c**2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [18]:
#indexing with arrays and using arrays for data processing
a[0]

6

In [19]:
b[1,2]

6

In [20]:
c[0,1]

8.0

In [21]:
d[1, 0:2]

array([9., 8.])

In [22]:
e = np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])
e[:3, :2] #slicing

array([[10, 11],
       [13, 14],
       [16, 17]])

In [23]:
#integer indexing
e[[2,0,3,1],[2,1,0,2]]

array([18, 11, 19, 15])

In [24]:
#boolean indexing meeting a specified condition
e[e>15]

array([16, 17, 18, 19, 20, 21])

###Pandas

In [25]:
import pandas as pd

In [26]:
days = pd.Series(['Monday','Tuesday','Wednesday'])
print(days)

0       Monday
1      Tuesday
2    Wednesday
dtype: object


In [27]:
#creating series with numpy arrays
days_list = np.array(['Monday','Tuesday','Wednesday'])
numpy_days = pd.Series(days_list)
print(numpy_days)
print(days_list)

0       Monday
1      Tuesday
2    Wednesday
dtype: object
['Monday' 'Tuesday' 'Wednesday']


In [28]:
#using strings as index
days = pd.Series(['Monday','Tuesday','Wednesday'], index = ['a','b','c'])
#create series from a dictionary
days1 = pd.Series({'a':'Monday','b':'Tuesday','c':'Wednesday'})
print(days)
print(days1)

a       Monday
b      Tuesday
c    Wednesday
dtype: object
a       Monday
b      Tuesday
c    Wednesday
dtype: object


In [29]:
#accessing series using specified index
days[0]

'Monday'

In [30]:
days[1: ]

b      Tuesday
c    Wednesday
dtype: object

In [31]:
days['c']

'Wednesday'

In [32]:
#print an empty dataframe
print(pd.DataFrame())

Empty DataFrame
Columns: []
Index: []


In [33]:
#create a dataframe from a dictionary
df_dict = {'Country': ['Ghana','Kenya','Nigeria','Togo'], 
           'Capital': ['Accra', 'Nairobi', 'Abuja','Lome'],
           'Population': [10000, 8500, 35000, 12000],
           'Age': [60, 70, 80, 75]
           }

In [34]:
df = pd.DataFrame(df_dict, index = [2,4,6,8])
print(df)

   Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75


In [36]:
df_list = [['Ghana','Accra', 10000, 60],
           ['Kenya','Nairobi', 8500, 70],
           ['Nigeria','Abuja', 35000, 80],
           ['Togo','Lome', 12000, 75]] 

In [38]:
df1 = pd.DataFrame(df_list, index = [2,4,6,8], columns = 
                   ['Country','Capital','Population','Age'])
print(df1)

   Country  Capital  Population  Age
2    Ghana    Accra       10000   60
4    Kenya  Nairobi        8500   70
6  Nigeria    Abuja       35000   80
8     Togo     Lome       12000   75


In [39]:
#selects the row at index 3
df.iloc[3]

Country        Togo
Capital        Lome
Population    12000
Age              75
Name: 4, dtype: object

In [41]:
#select row with index label 3
df.loc[3]

Country       Nigeria
Capital         Abuja
Population      35000
Age                80
Name: 3, dtype: object

In [42]:
#select Capital column
df['Capital']

1      Accra
2    Nairobi
3      Abuja
4       Lome
Name: Capital, dtype: object

In [43]:
df.at[3, 'Country']

'Nigeria'

In [44]:
df.iat[2,0]

'Nigeria'

In [45]:
#summary and descriptive stats in pandas
df['Population'].sum()

65500

In [46]:
df.mean()

Population    16375.00
Age              71.25
dtype: float64

In [47]:
df.describe()

Population        Age
count      4.000000   4.000000
mean   16375.000000  71.250000
std    12499.166639   8.539126
min     8500.000000  60.000000
25%     9625.000000  67.500000
50%    11000.000000  72.500000
75%    17750.000000  76.250000
max    35000.000000  80.000000

In [49]:
#handling missing data
df_dict2 = {'Name':['James','Yemen','Caro', np.nan],
            'Profession':['Researcher','Artist','Doctor','Writer'],
            'Experience':[12, np.nan, 10, 8],
            'Height': [np.nan, 175, 180, 150]}
new_df = pd.DataFrame(df_dict2)
new_df

Name  Profession  Experience  Height
0  James  Researcher        12.0     NaN
1  Yemen      Artist         NaN   175.0
2   Caro      Doctor        10.0   180.0
3    NaN      Writer         8.0   150.0

In [50]:
new_df.isnull() #check for cells with missing values

Name  Profession  Experience  Height
0  False       False       False    True
1  False       False        True   False
2  False       False       False   False
3   True       False       False   False

In [51]:
#remove rows with missing values
new_df.dropna()

Name Profession  Experience  Height
2  Caro     Doctor        10.0   180.0

###Data Types and Data Wrangling

In [52]:
csv_df = pd.read_csv('sample_file.csv')
csv_df.to_csv('sample_file.csv',index=False)

FileNotFoundError: ignored

In [53]:
excel_df = pd.read_excel('sample_file.xlsx')
excel_df.to_excel('sample_file.xlsx')

FileNotFoundError: ignored

In [54]:
html_df = pd.read_html('http://www.webpage.com/sampledata.html')
html_df.to_html('sample_file.html')

HTTPError: ignored

In [56]:
#read in the fuel dataset
url = 'https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv'
fuel_data = pd.read_csv(url, error_bad_lines = False)
fuel_data.describe(include = 'all')

record_id  ...  fuel_cost_per_mmbtu
count                     29523  ...         29523.000000
unique                    29523  ...                  NaN
top     f1_fuel_2012_12_150_0_4  ...                  NaN
freq                          1  ...                  NaN
mean                        NaN  ...            19.304354
std                         NaN  ...          2091.540939
min                         NaN  ...           -41.501000
25%                         NaN  ...             1.940000
50%                         NaN  ...             4.127000
75%                         NaN  ...             7.745000
max                         NaN  ...        359278.000000

[11 rows x 11 columns]

In [57]:
fuel_data.head()

record_id  ...  fuel_cost_per_mmbtu
0   f1_fuel_1994_12_1_0_7  ...                1.121
1  f1_fuel_1994_12_1_0_10  ...                1.120
2   f1_fuel_1994_12_2_0_1  ...                1.650
3   f1_fuel_1994_12_2_0_7  ...                1.970
4  f1_fuel_1994_12_2_0_10  ...                2.570

[5 rows x 11 columns]

In [59]:
fuel_data.shape

(29523, 11)

In [58]:
fuel_data.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64