<a href="https://colab.research.google.com/github/sumusa/Hamoye-Internship-Notes/blob/master/Hamoye_Stage_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###NumPy Array and Vectorization

In [1]:
#convention for importing numpy
import numpy as np

In [2]:
arr = [6,7,8,9]
print(type(arr))

<class 'list'>


In [3]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [6]:
print(a.shape)

(4,)


In [7]:
print(a.dtype)

int64


In [8]:
#get the dimension of 'a'
print(a.ndim)
#a is a 1d array with 4 items

1


In [10]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
print(b.ndim)
b.shape
#b is a 2d array with 2 rows and 3 columns

2


(2, 3)

In [13]:
#to generate a 2*3 array with random values
np.random.random((2,3))

array([[0.85415421, 0.57246884, 0.41852863],
       [0.77369179, 0.07334472, 0.926546  ]])

In [14]:
#to generate a 2*3 array of zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
#to generate a 2*3 array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
#to genarate a 3*3 identity matrix
np.zeros(3)

array([0., 0., 0.])